---
dotfiles_dir: "{{ ansible_env.HOME }}/.dotfiles"
config_dir: "{{ ansible_env.HOME }}/.config"

common_packages:
  - git
  - curl
  - wget
  - ripgrep
  - fzf
  - jq
  - tree
  - htop
  - lazygit

dev_languages:
  - node
  - python
  - go
  - rust
  - java

macos_casks:
  - visual-studio-code
  - ghostty

ubuntu_packages:
  - build-essential
  - snapd
  - libssl-dev
  - pkg-config